a=int(input("Enter first number:"))
b=int(input("Enter second number:"))
print("*****COmparision Operators*****")
print("is equals:",a==b)
print("is not equals:",a!=b)
print("greater than:",a>b)
print("less than:",a<b)
print("greater than equal:",a>=b)
print("less than equal:",a<=b)
